"""Real-browser acceptance checks, run against a temporary local server."""
from pathlib import Path
import json
import os
from playwright.sync_api import sync_playwright

BASE=os.getenv('TEST_BASE_URL','http://127.0.0.1:8765')
LOCAL=os.getenv('TEST_LOCAL_URL','http://127.0.0.1:8766/')
ART=Path(os.getenv('TEST_ARTIFACT_DIR',str(Path(__file__).resolve().parents[1]/'test-artifacts')));ART.mkdir(exist_ok=True)
PASSWORD='browser-test-only-very-long-password'
errors=[]
results=[]

def check(value,msg):
    assert value,msg
    results.append(msg)

with sync_playwright() as p:
    browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    local_context=browser.new_context(viewport={'width':1440,'height':1080},locale='ru-RU',reduced_motion='reduce')
    page=local_context.new_page()
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(LOCAL)
    page.wait_for_selector('[data-card="g1"]')
    check(page.locator('.goal-card').count()==6,'local: six cards')
    check(page.locator('.local-banner').count()==0,'local: removed banner stays absent')
    page.screenshot(path=str(ART/'dashboard-desktop.png'),full_page=True)
    page.locator('[data-goal="g5"]').click()
    page.locator('#g5s1').check()
    page.wait_for_function('document.querySelector(".ring-label strong").textContent==="17%"')
    page.locator('[data-tab="result"]').click()
    page.locator('#g5c1').check()
    page.wait_for_selector('.notice.success')
    page.locator('.drawer-head [data-action="close"]').click()
    page.reload()
    page.wait_for_selector('[data-card="g5"] .tag.accepted')
    check(page.locator('[data-card="g5"] .tag.accepted').is_visible(),'local: accepted result survives reload')
    page.locator('[data-view="map"]').first.click()
    check(page.locator('.map-node').count()==6,'local: interactive map has six nodes')
    page.locator('[data-goal="g4"]').click()
    page.locator('[data-action="wheel"]').click()
    for area,v in [('work',8),('family',6),('health',7),('growth',7),('rest',5),('finance',7)]:
        page.locator('#wheel-'+area).fill(str(v))
    page.locator('#reflection').fill('Личная тестовая заметка, не для группы')
    page.locator('form[data-form="wheel"] button[type=submit]').click()
    page.wait_for_selector('.drawer')
    page.locator('.drawer-head [data-action="close"]').click()
    page.locator('[data-action="menu"]').click()
    page.locator('[data-action="report"]').click()
    text=page.locator('#report-content').input_value()
    check('Личная тестовая заметка' not in text,'local: report excludes private wheel reflection')
    page.locator('.modal-head [data-action="close"]').click()
    page.locator('[data-view="dynamics"]').first.click()
    check(page.locator('.chart-svg').count()==1,'local: real progress history chart appears')
    page.screenshot(path=str(ART/'dashboard-history.png'),full_page=True)
    # Separate mobile browser, no pre-seeded progress.
    mobile_context=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,device_scale_factor=1,locale='ru-RU',reduced_motion='reduce')
    mobile=mobile_context.new_page();mobile.on('pageerror',lambda e:errors.append(str(e)))
    mobile.goto(LOCAL);mobile.wait_for_selector('.goals-grid')
    check(mobile.evaluate('document.documentElement.scrollWidth <= window.innerWidth'),'mobile: overview has no horizontal overflow')
    mobile.screenshot(path=str(ART/'dashboard-mobile.png'),full_page=True)
    mobile.locator('[data-view="map"]').first.click()
    check(mobile.evaluate('document.documentElement.scrollWidth <= window.innerWidth'),'mobile: map has no horizontal overflow')
    mobile.locator('[data-goal="g1"]').click()
    check(mobile.locator('#g1s1').is_visible(),'mobile: drawer checklist accessible')
    mobile.screenshot(path=str(ART/'dashboard-mobile-drawer.png'),full_page=True)
    mobile_context.close()
    # The actual shared app, not a role switch in the browser.
    owner_context=browser.new_context(viewport={'width':1440,'height':1080},locale='ru-RU',reduced_motion='reduce')
    owner=owner_context.new_page();owner.on('pageerror',lambda e:errors.append(str(e)))
    owner.goto(BASE);owner.wait_for_selector('form[data-form="auth"]')
    if owner.locator('#auth-code').count():
        owner.locator('#auth-code').fill('dashboard-browser-test-only')
        owner.locator('#auth-name').fill('Максим')
    owner.locator('#auth-username').fill('maxim')
    owner.locator('#auth-password').fill(PASSWORD)
    owner.locator('form[data-form="auth"] button[type=submit]').click()
    owner.wait_for_selector('[data-card="g1"]')
    check(owner.locator('.local-banner').count()==0,'server: hosted UI not labelled local')
    owner.locator('[data-action="share"]').click()
    owner.locator('#invite-name').fill('Друг по мастермайнду')
    owner.locator('form[data-form="invite"] button[type=submit]').click()
    owner.wait_for_selector('#invite-link')
    invite=owner.locator('#invite-link').input_value()
    check('#invite=' in invite,'server: invite token is a URL fragment')
    guest_context=browser.new_context(viewport={'width':1280,'height':960},locale='ru-RU',reduced_motion='reduce')
    guest=guest_context.new_page();guest.on('pageerror',lambda e:errors.append(str(e)))
    guest.goto(invite)
    guest.wait_for_selector('#auth-name')
    guest.locator('#auth-name').fill('Тестовый участник')
    import time
    guest.locator('#auth-username').fill('friend'+str(int(time.time())))
    guest.locator('#auth-password').fill(PASSWORD)
    guest.locator('form[data-form="auth"] button[type=submit]').click()
    guest.wait_for_selector('[data-card="g1"]')
    check('#invite=' not in guest.url,'server: invitation removed from address bar')
    guest.locator('[data-goal="g1"]').click()
    check(guest.locator('#g1s1').is_disabled(),'server: guest step controls are disabled')
    guest.locator('[data-tab="comments"]').click()
    guest.locator('#comment-text').fill('Проверка совместного комментария')
    guest.locator('[data-action="submit-comment"]').click()
    guest.wait_for_selector('.comment')
    check('Проверка совместного комментария' in guest.locator('#comment-list').inner_text(),'server: guest comment saved')
    owner.locator('.modal-head [data-action="close"]').click()
    owner.locator('[data-view="discussion"]').first.click()
    owner.wait_for_selector('.comment',timeout=16000)
    check('Проверка совместного комментария' in owner.locator('#comment-list').inner_text(),'server: another session receives shared comment')
    owner.locator('[data-view="overview"]').first.click()
    owner.screenshot(path=str(ART/'dashboard-server.png'),full_page=True)
    check(not errors,'browser: no JavaScript errors')
    browser.close()

print(json.dumps({'passed':len(results),'checks':results,'errors':errors},ensure_ascii=False,indent=2))
